version: "3.9"
services:
  db:
    image: postgres:13.4
    ports:
      - "${PGPORT}:5432"
    volumes:
      - /media/user/vault/pgdata/fhirplayground:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
